remote_theme: robmoffat/bot-jekyll-theme
title: Spring Bot
name: Spring Bot
subtitle: Annotation-driven bot creation framework for Microsoft Teams and Symphony
description: Annotation-driven bot creation framework for Microsoft Teams and Symphony
email: rob@kite9.com
baseurl: "/spring-bot" # the subpath of your site, e.g. /blog
include: ['_pages']
url: https://finos.github.io/spring-bot
author: Finos

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# build settings
markdown: kramdown

sass:
  style: compressed
