remote_theme: robmoffat/bot-jekyll-theme
title: Spring Bot
name: Spring Bot
subtitle: Annotation-driven bot creation framework for Microsoft Teams and Symphony
description: Annotation-driven bot creation framework for Microsoft Teams and Symphony
email: rob@kite9.com
baseurl: "/" # the subpath of your site, e.g. /blog
include: ['_pages']
url: https://springbot.finos.org
author: Finos

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# build settings
markdown: kramdown

sass:
  style: compressed
