name: License Scanning for Maven

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'maven/pom.xml'
      - '.github/workflows/license-check.yml'
      - '.github/workflows/acceptable-licenses.txt'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 8
        cache: maven
        distribution: 'adopt'
    - name: Build 
      run: mvn install -DskipTests
    - name: License XML report
      run: mvn org.codehaus.mojo:license-maven-plugin:2.0.0:download-licenses
    - name: Validate XML report
      run: |
        find libs | grep licenses.xml | awk '{print "cat " $1}' | sh | grep "<name>" | sed 's/^\ *//' | sort | uniq > target/complete-licenses.txt
        comm -23 target/complete-licenses.txt .github/workflows/acceptable-licenses.txt > target/license-report.txt
        LINES_FOUND=`cat target/license-report.txt | wc -l`
        echo "License issues found ..."
        if [ $LINES_FOUND -gt 1 ]; then cat target/license-report.txt ; exit -1; fi
      working-directory: maven
    - name: Upload license reports
      uses: actions/upload-artifact@v3
      with:
        name: license-reports
        path: 'maven/**/dependencies.html'
    - name: Upload license XML reports
      uses: actions/upload-artifact@v3
      with:
        name: license-xml-report
        path: 'maven/**/${{ env.REPORT_PATH }}' 
